# Generated by Django 5.1.4 on 2025-01-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vote_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='description',
            new_name='desc',
        ),
    ]
