# Generated by Django 5.1.4 on 2025-01-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_description_community_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='score',
            new_name='karma',
        ),
    ]
