# Generated by Django 5.1.4 on 2024-12-26 14:07

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_groups_remove_user_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('rating_1', models.IntegerField(default=0)),
                ('rating_2', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('rating_3', models.FloatField(default=0)),
                ('join_date', models.DateField(default=datetime.date(2021, 2, 25))),
                ('transaction_timestamp', models.DateTimeField(default=datetime.datetime(2022, 9, 1, 1, 2, 30))),
                ('camelCaseTest', models.BooleanField()),
                ('PascalCaseTest', models.BigIntegerField(default=0)),
                ('SCREAMING_SNAKE_CASE_TEST', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
